#!/bin/bash
# Quick VPS Verification Commands
# Copy and paste these after deployment

echo "═══════════════════════════════════════════════════════════"
echo "AMARKTAI NETWORK - VPS VERIFICATION COMMANDS"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  OPENAPI JSON (must be >50KB, not 716 bytes HTML)"
echo "────────────────────────────────────────────────────────────"
echo "curl -fsS https://www.amarktai.online/api/openapi.json | wc -c"
echo ""
echo "curl -fsS https://www.amarktai.online/api/openapi.json | head -20"
echo ""
echo "curl -fsS https://www.amarktai.online/api/openapi.json | jq . | grep '/api/auth/login'"
echo ""

echo "2️⃣  DOCS & REDOC UI"
echo "────────────────────────────────────────────────────────────"
echo "curl -I https://www.amarktai.online/api/docs"
echo ""
echo "curl -I https://www.amarktai.online/api/redoc"
echo ""

echo "3️⃣  HEALTH CHECK"
echo "────────────────────────────────────────────────────────────"
echo "curl -fsS https://www.amarktai.online/api/health/ping"
echo ""

echo "4️⃣  AUTH RESPONSE FORMAT (requires credentials)"
echo "────────────────────────────────────────────────────────────"
echo "# Login and check response has access_token only"
echo "curl -X POST https://www.amarktai.online/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"YOUR_EMAIL\",\"password\":\"YOUR_PASSWORD\"}' | jq ."
echo ""
echo "# Verify NO duplicate 'token' field (should return: false)"
echo "curl -X POST https://www.amarktai.online/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"YOUR_EMAIL\",\"password\":\"YOUR_PASSWORD\"}' | jq 'has(\"token\")'"
echo ""

echo "5️⃣  ADMIN ENDPOINTS (must be protected)"
echo "────────────────────────────────────────────────────────────"
echo "curl -I https://www.amarktai.online/api/admin/users"
echo "# Expected: 401 Unauthorized"
echo ""
echo "curl -I https://www.amarktai.online/api/admin/overview"
echo "# Expected: 401 Unauthorized"
echo ""

echo "6️⃣  API KEYS ENDPOINTS"
echo "────────────────────────────────────────────────────────────"
echo "# Providers list (public, no auth)"
echo "curl -fsS https://www.amarktai.online/api/keys/providers | jq ."
echo ""
echo "# Status endpoint (protected, should fail without auth)"
echo "curl -I https://www.amarktai.online/api/keys/status"
echo "# Expected: 401 Unauthorized"
echo ""

echo "7️⃣  BUILD INFO"
echo "────────────────────────────────────────────────────────────"
echo "curl -fsS https://www.amarktai.online/api/build/info | jq ."
echo ""

echo "8️⃣  FRONTEND SPA"
echo "────────────────────────────────────────────────────────────"
echo "curl -I https://www.amarktai.online/"
echo "# Expected: 200 OK, Content-Type: text/html"
echo ""

echo "9️⃣  AUTOMATED VERIFICATION"
echo "────────────────────────────────────────────────────────────"
echo "bash scripts/verify_live.sh"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo ""
echo "EXPECTED RESULTS SUMMARY:"
echo "  ✅ OpenAPI JSON: >50KB, valid JSON"
echo "  ✅ Auth response: Has access_token, NO token field"
echo "  ✅ Admin endpoints: Return 401 without auth"
echo "  ✅ Docs/ReDoc: Return 200"
echo "  ✅ Health: Returns ok status"
echo ""
echo "For detailed verification, see:"
echo "  - ACCEPTANCE_TESTS.md"
echo "  - VERIFICATION.md"
echo "  - PR_DESCRIPTION.md"
echo ""
echo "═══════════════════════════════════════════════════════════"
